version: '3.8'

services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - ./logs:/logs
    ports:
      - "5000:5000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./logs:/logs
    depends_on: flask-server

