version: '3.8'

services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - ./logs:/logs
    ports:
      - "5000:5000"
    depends_on:
      - client

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - ./logs:/logs
    ports:
      - "5001:5001"
